device_id: "my-thermocktat"
controllers:
  http:
    enabled: true
    addr: ":8080"
  mqtt:
    enabled: true
    broker_url: "tcp://host.docker.internal:1883"
    qos: 0
    retain_snapshot: true
    publish_interval: 1s
  modbus:
    enabled: true
    addr: "localhost:1502"
    unit_id: 4

thermostat:
  enabled: true
  ambient_temperature: 21.0
  temperature_setpoint: 22.0
  temperature_setpoint_min: 16.0
  temperature_setpoint_max: 28.0
  mode: "auto"
  fan_speed: "auto"

regulator:
  enabled: true
  interval: 1s
  kp: 0.1
  ki: 0.01
  kd: 0.05
  trigger_hysteresis: 1
  target_hysteresis: 0.5
