device_id: "my-thermocktat"
controllers:
  http:
    enabled: true
    addr: ":8080"
  mqtt:
    enabled: false
    addr: "tcp://host.docker.internal:1883"
    qos: 0
    retain_snapshot: false
    publish_interval: 5s
  modbus:
    enabled: false
    addr: "localhost:1502"
    unit_id: 4

thermostat:
  enabled: true
  ambient_temperature: 21.0
  temperature_setpoint: 22.0
  temperature_setpoint_min: 16.0
  temperature_setpoint_max: 28.0
  mode: "auto"
  fan_speed: "auto"

regulator:
  enabled: true
  interval: 1s
  kp: 0.00001
  ki: 0.00001
  kd: 0.01
  mode_change_hysteresis: 2.0 # used for switching between heating and cooling in auto mode.
  target_hysteresis: 1.0

heat_loss:
  coefficient: 0.0001 # 0, represents conductivity. 0 for no loss.
  outdoor_temperature: 10
